### ISSUE TITLE
Deploy on basic network

### ISSUE THREAD

**Issue by edwardtamkingfai** [IBM/blockchainbean2#6]
Can you please show how to deploy the contract on a "basic-network" found on Hyperledger's fabric-samples?

Would like to try this out on this instead of "local fabric" generated by Visual Studio.

Thanks.

**Comment by horeaporutiu** [comment]
Currently, creating documentation to show how to deploy this contract on "basic-network" is not a high priority. The reason is that the documentation is already there - https://hyperledger-fabric.readthedocs.io/en/release-1.4/tutorial/commercial_paper.html?highlight=basic-network. Instead of pointing the peer chaincode install command to the `commercialpaper/organization/magnetocorp/contract` directory, you would point it to the `https://github.com/IBM/blockchainbean2/tree/master/lib` directory on your local computer. After that, the commands are more or less the same.
